language: php
php:
  # No PHP 5.5, as phpunit does not support it.
  - 5.6
  - 7.0
install: composer install
# Only run the unit tests; for the integration tests we need a Drupal install.
script: vendor/phpunit/phpunit/phpunit Test/Unit
